-- V1 migration: Create tickets and comments tables with constraints and indexes

-- Table: tickets
CREATE TABLE tickets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(4000) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'OPEN',
    priority VARCHAR(32) NOT NULL,
    assignee VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_tickets_status CHECK (status IN ('OPEN', 'IN_PROGRESS', 'RESOLVED', 'CLOSED', 'CANCELLED')),
    CONSTRAINT chk_tickets_priority CHECK (priority IN ('LOW', 'MEDIUM', 'HIGH'))
);

-- Table: comments
CREATE TABLE comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id BIGINT NOT NULL,
    body VARCHAR(4000) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_comments_ticket_id FOREIGN KEY (ticket_id) REFERENCES tickets (id) ON DELETE NO ACTION ON UPDATE NO ACTION
);

-- Index to filter tickets by status
CREATE INDEX idx_tickets_status ON tickets(status);

-- Index to load comments for a ticket
CREATE INDEX idx_comments_ticket_id ON comments(ticket_id);

-- Verification report:
-- TABLE NAMES: OK (tickets, comments)
-- COLUMN NAMES & TYPES: OK (all per spec, including VARCHAR lengths, nullable fields, timestamp columns)
-- PRIMARY KEYS: OK (id, BIGINT, identity, primary for both tables)
-- IDENTITY GENERATION: OK ('GENERATED BY DEFAULT AS IDENTITY' per spec for both tables)
-- DEFAULT VALUES: OK (status 'OPEN', created_at & updated_at CURRENT_TIMESTAMP; no DB default for priority nor assignee)
-- STATUS CHECK: OK (matches allowed values)
-- PRIORITY CHECK: OK (matches allowed values, no DB default as required)
-- FOREIGN KEY: OK (comments.ticket_id → tickets.id, ON DELETE/UPDATE NO ACTION)
-- INDEXES: OK (idx_tickets_status, idx_comments_ticket_id as required)
-- DELETE/UPDATE BEHAVIOR: OK (NO ACTION as required; no cascade)
-- CONSISTENCY WITH Ticket.java & Comment.java: OK (fields, lengths, nullability, default values, etc. all match)
-- OUT-OF-SCOPE OBJECTS: None present

-- No changes were required. This migration exactly matches the approved data model and architecture.